name: NPM Audit Actions

on: [pull_request]

jobs:
  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: npm ci
      - name: Run NPM audit
        run: npm audit --json > report.json
      - name: Publish report
        run: npm run sca
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      